apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZGVtb0AxMjM=             #demo@123
  MYSQL_USER: a3Jpc2h1c2Vy                      #krishuser
  MYSQL_PASSWORD: a3Jpc2gxMjM0                  #krish1234
  MYSQL_DATABASE: a3Jpc2hfY29udGFjdGJk          #krish_contactdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-db-app-deployment
  namespace: default
  labels:
    app: crud-db-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-db-app
  template:
    metadata:
      labels:
        app: crud-db-app
    spec:
      containers:
        - name: crud-db-app-container
          image: krishhub/crud-db-app
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 256Mi
          env:
            # Set environment variables for the database connection
            - name: MYSQL_ROOT_HOST
              value: crud-db-service
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-mysqldb-app
  namespace: default
  labels:
    app: crud-mysqldb-app
spec:
  selector:
    matchLabels:
      app: crud-mysqldb-app
  replicas: 1
  template:
    metadata:
      labels:
        app: crud-mysqldb-app
    spec:
      automountServiceAccountToken: true
      containers:
      - name: crud-mysqldb-app
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: my-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: crud-db-service
  namespace: default
  labels:
    app: crud-db-services
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: crud-mysqldb-app
---
# Expose the deployment as a NodePort service
apiVersion: v1
kind: Service
metadata:
  name: crud-db-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: crud-db-app
  ports:
    - name: http
      port: 80
      targetPort: 80